# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'Subscriber',
            },
        ),
    ]
